Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [31]:
def descented_arange ():
    input_number = int(input('Введите число: '))
    a = np.arange(0, input_number)
    b = a[::-1]
    return b

descented_arange()

Введите число: 6


array([5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [38]:
my_array = np.diag(descented_arange(), k=0)
print(my_array)
i = 0
summary = 0
for row in my_array:
    summary += row[i]
    i += 1
print(f'Сумма значений матрицы из {my_array.shape [1]} убывающих порядковых чисел по диагонали = {summary}')

Введите число: 8
[[7 0 0 0 0 0 0 0]
 [0 6 0 0 0 0 0 0]
 [0 0 5 0 0 0 0 0]
 [0 0 0 4 0 0 0 0]
 [0 0 0 0 3 0 0 0]
 [0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0]]
Сумма значений матрицы из 8 убывающих порядковых чисел по диагонали = 28


Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [4]:
from numpy import linalg
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [5]:
# проверка верности
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
На сайт заходит очередной посетитель, о покупках которого известно следующее:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [6]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [7]:
new_user = np.array([0, 1, 2, 0, 0, 0])

In [42]:
#Пробуем работу функции по косинусному сравнению на массиве данных по одному пользователю из матрицы пользователей
next_user1 = np.array([2, 1, 0, 0, 0, 0])
def cosine (next_user1, new_user):
    next_length1 = np.linalg.norm( next_user1 )
    new_length = np.linalg.norm( new_user )
    return np.dot( next_user1, new_user ) / ( next_length1 * new_length )

cosine (next_user1, new_user)

0.19999999999999996

In [49]:
#Функция делает косинусное сравнение между новым и текущим пользователем, результат - угол между векторами в градусах
def arccos (next_user, new_user):
    next_length = np.linalg.norm( next_user )
    new_length = np.linalg.norm( new_user )
    return np.arccos (np.dot( next_user, new_user ) / ( next_length * new_length ) ) * 360 / 2 / np.pi

max_arccos = 90
max_user = []
for next_user in users_stats:
    next_arccos = arccos (next_user, new_user)
    #print(next_arccos)
    if next_arccos < max_arccos:
        max_arccos = next_arccos
        max_user = next_user
print(f'Минимальный угол между векторами - {round(max_arccos, 1)} градусов')
print(f'Самый похожий пользователь - {max_user}')

Минимальный угол между векторами - 18.4 градусов
Самый похожий пользователь - [0 1 1 0 0 0]
